# Copy this file to: Camille-Tran-Website/.github/workflows/template-sync.yml

name: Sync from Template Repository

on:
  # Run manually from Actions tab
  workflow_dispatch:
  
  # Run automatically on schedule (once a day at 2 AM)
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync template changes from Camille-Tran-Web
    
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEMPLATE_SYNC_TOKEN }}
      
      - name: Run template sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          # IMPORTANT: The template repository to pull changes from
          source_repo_path: Ctt011/Camille-Tran-Web
          
          # Branch in template repo to sync from
          upstream_branch: main
          
          # Token with access to BOTH repositories (UPDATED PARAMETER NAME)
          source_repo_ssh_private_key: ''  # Leave empty if using token
          source_gh_token: ${{ secrets.TEMPLATE_SYNC_TOKEN }}
          
          # PR settings
          pr_labels: template-sync,automated
          pr_title: "🔄 Sync template changes from Camille-Tran-Web"
          pr_body: |
            ## Template Sync
            
            This PR contains the latest updates from the **Camille-Tran-Web** template repository.
            
            ### What's included:
            - Latest code changes
            - Bug fixes  
            - New features
            
            ### Action required:
            ✅ Review the changes
            ✅ Test locally if needed
            ✅ Merge when ready
            
            ---
            🤖 Auto-generated by GitHub Actions
          
          pr_branch_name_prefix: template-sync-
          pr_commit_msg: "chore: sync template changes from Camille-Tran-Web"
